###
# installer
##
# Add lockfile and package.json's of isolated subworkspace
FROM node:alpine AS installer
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app

RUN yarn install

###
# runner
##
FROM node:latest AS runner
WORKDIR /app

COPY --from=installer /app .

CMD yarn turbo run dev --scope=@mqs/web
