services:
  web:
    volumes:
      - ./:/app
    build:
      dockerfile: ./apps/web/Dockerfile.dev
  api:
    volumes:
      - ./:/app
    build:
      dockerfile: ./apps/api/Dockerfile.dev
  db:
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network
volumes:
  app:
