services:
  web:
    build:
      dockerfile: ./apps/web/Dockerfile.prod
    env_file:
      - .env.prod
  api:
    build:
      dockerfile: ./apps/api/Dockerfile.prod
    env_file:
      - .env.prod
  db:
    env_file:
      - .env.prod
