services:
  web:
    volumes:
      - ./:/app
    build:
      dockerfile: ./apps/web/Dockerfile.dev
    env_file:
      - .env.dev
  api:
    volumes:
      - ./:/app
    build:
      dockerfile: ./apps/api/Dockerfile.dev
    env_file:
      - .env.dev
  db:
    env_file:
      - .env.dev
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network
volumes:
  app:
