services:
  web:
    volumes:
      - ./:/app
    build:
      dockerfile: ./apps/web/Dockerfile.dev
    env_file:
      - .env.dev
  api:
    volumes:
      - ./:/app
    build:
      dockerfile: ./apps/api/Dockerfile.dev
    env_file:
      - .env.dev
  db:
    env_file:
      - .env.dev
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network
  dev:
    volumes:
      - ./:/app
    working_dir: /app
    image: node:latest # TODO: revert to alpine and add bycrypt deps https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions
    container_name: dev
    restart: always
    env_file:
      - .env.dev
    tty: true
    networks:
      - app_network
volumes:
  app:
