version: "3"

services:
  web:
    container_name: web
    build:
      context: .
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - app_network

networks:
  app_network:
    external: false
